##################################################################################################
#  Hola
##################################################################################################
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hola-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hola
        version: "2.0"
    spec:
      containers:
      - name: spring-boot
        image: hola:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
